### ISSUE TITLE
Susa migration

### ISSUE THREAD

**Issue by chase-moskal** [ChaseMoskal/Nanoshooter#45]
It's time that the framework is separated into its own repository.
## Criteria
- [x] Create "Susa" repo.
- [x] Separate readme's.
- [x] Establish the [Susa repo.](https://github.com/AkkadianGames/Susa)
- [x] Git submodule for Susa within Nanoshooter — devs can work on both projects simultaneously.
- [x] Move framework code to Susa repo.
## Should be re-ticketed:
- [x] Reasonable process for publishing to `gh-pages` (#54).
- [x] Separate the roadmaps on Trello (#55).
- [x] Migrate Nanoshooter framework issues to Susa (#56)
