### ISSUE TITLE
Repo url change

### ISSUE THREAD

**Issue by chase-moskal** [ChaseMoskal/Nanoshooter#47]
We transferred repo ownership to the new organization, thus changing the links, thus creating problems and work to do.

Link used to be:
- https://github.com/ChaseMoskal/Nanoshooter

Now it's:
- https://github.com/AkkadianGames/Nanoshooter

We've got to address this repository rename in several ways.
## Tasks to do:
- [x] Make sure the URL is totally finalized in #46.
- [x] Fix travis ci.
- [x] Fix readme links.
- [x] Fix sandbox infopanel links.

**Comment by chase-moskal** [comment]
## Done.
